spring:
  application:
    name: kafka-producer-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  zipkin:
    base-url: http://localhost:9411/

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: /logs/producer.log
  level:
    root: INFO
    com.mp.fintech: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"